"""Build the project-page reading catalogue from the repository's Markdown lists.

Run after editing papers/*.md. --check verifies the checked-in browser data.
"""
from pathlib import Path
import argparse
import html
import json
import re

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'docs/assets/catalogue.js'
SCOPES = ['artifacts', 'processes', 'equipment', 'production', 'fabs']


def plain(value):
    for _ in range(3):
        decoded = html.unescape(value)
        if decoded == value:
            break
        value = decoded
    return value.strip()


def build():
    tasks = []
    papers = []
    for scope in SCOPES:
        lines = (ROOT / 'papers' / f'{scope}.md').read_text(encoding='utf-8').splitlines()
        task = None
        for i, line in enumerate(lines):
            heading = re.match(r'^## ([APERF]\d) · (.+)$', line)
            if heading:
                task = {'id': heading[1], 'title': plain(heading[2]), 'scope': scope, 'question': ''}
                tasks.append(task)
            elif line.startswith('> ') and task and not task['question']:
                task['question'] = plain(line[2:])
            elif line.startswith('- <a id='):
                match = re.fullmatch(r'- <a id="([^"]+)"></a>\*\*\[(.*)\]\((.*)\)\*\*<br>', line)
                if not match or not task:
                    raise ValueError(f'Unrecognized paper entry: {scope}:{i+1}')
                metadata = re.fullmatch(r'\s*(\d{4}) · (.*?) · \*(.*?)\*(.*)', lines[i+1])
                if not metadata:
                    raise ValueError(f'Unrecognized metadata: {scope}:{i+2}')
                url = plain(match[3])
                if not url.startswith(('https://', 'http://')):
                    raise ValueError(f'Unsupported paper URL: {url}')
                papers.append({'id': match[1], 'title': plain(match[2]), 'url': url,
                               'year': int(metadata[1]), 'authors': plain(metadata[2]),
                               'venue': plain(metadata[3]), 'task': task['id'], 'scope': scope,
                               'resources': [{'label':plain(label),'url':plain(link)} for label,link in re.findall(r'\[([^\]]+)\]\(([^)]+)\)',metadata[4])]})
    assert len(tasks) == 19 and len({t['id'] for t in tasks}) == 19
    assert len(papers) == len({p['id'] for p in papers})
    assert all(t['question'] for t in tasks)
    bibkeys = set(re.findall(r'^@\w+\{([^,\s]+),', (ROOT/'references.bib').read_text(encoding='utf-8'), re.M))
    assert {p['id'] for p in papers} == bibkeys, 'Reading list and BibTeX coverage differ'
    content = '// Generated by scripts/build_catalogue.py from papers/*.md.\nwindow.MANUFACTURING_CATALOGUE = '+json.dumps({'tasks':tasks,'papers':papers}, ensure_ascii=False,separators=(',',':'))+';\n'
    return content, len(papers)


if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    content,count=build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != content:
            raise SystemExit('Browser catalogue is stale. Run python scripts/build_catalogue.py')
    else:
        OUTPUT.parent.mkdir(parents=True,exist_ok=True);OUTPUT.write_text(content,encoding='utf-8')
    print(f'19 tasks / {count} paper entries match the repository bibliography.')
