"""Build the project-page reading catalogue from the repository's Markdown lists.

Run after editing papers/*.md. --check verifies the checked-in browser data.
"""
from pathlib import Path
import argparse
import html
import json
import re
import csv
import io

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'docs/assets/catalogue.js'
SCOPES = ['artifacts', 'processes', 'equipment', 'production', 'fabs']


def plain(value):
    for _ in range(3):
        decoded = html.unescape(value)
        if decoded == value:
            break
        value = decoded
    return value.strip()


def build():
    coding = json.loads((ROOT / 'data/ai-stages.json').read_text(encoding='utf-8'))
    stages = coding['stages']
    tasks = []
    papers = []
    for scope in SCOPES:
        lines = (ROOT / 'papers' / f'{scope}.md').read_text(encoding='utf-8').splitlines()
        task = None
        for i, line in enumerate(lines):
            heading = re.match(r'^## ([APERF]\d) · (.+)$', line)
            if heading:
                task = {'id': heading[1], 'title': plain(heading[2]), 'scope': scope, 'question': ''}
                tasks.append(task)
            elif line.startswith('> ') and task and not task['question']:
                task['question'] = plain(line[2:])
            elif line.startswith('- <a id='):
                match = re.fullmatch(r'- <a id="([^"]+)"></a>\*\*(.*)\*\*<br>', line)
                if not match or not task:
                    raise ValueError(f'Unrecognized paper entry: {scope}:{i+1}')
                metadata = re.fullmatch(r'\s*(\d{4}) · (.*?) · \*(.*?)\*(.*?)<br>', lines[i+1])
                if not metadata:
                    raise ValueError(f'Unrecognized metadata: {scope}:{i+2}')
                links = re.findall(r'\[([^\]]+)\]\(([^)]+)\)', lines[i+2])
                assert links and links[0][0] == 'Paper ↗', f'Missing Paper chip: {match[1]}'
                url = plain(links[0][1])
                if not url.startswith(('https://', 'http://')):
                    raise ValueError(f'Unsupported paper URL: {url}')
                code = coding['papers'][match[1]]
                assert code['scope'] in SCOPES and len(code['stages']) == len(set(code['stages']))
                assert all(s in stages for s in code['stages'])
                assert code['stages'] or code.get('role') == 'Research testbed'
                expected = ['`'+s+' '+stages[s]+'`' for s in code['stages']] or ['`Research testbed`']
                assert re.findall(r'`[^`]+`', lines[i+2]) == expected, f'Stage chips differ: {match[1]}'
                papers.append({'id': match[1], 'title': plain(match[2]), 'url': url,
                               'year': int(metadata[1]), 'authors': plain(metadata[2]),
                               'venue': plain(metadata[3]), 'task': task['id'], 'scope': scope,
                               'stages': code['stages'], 'catalogueScope': code['scope'],
                               'preprint': '**Preprint**' in metadata[4],
                               'role': code.get('role', ''),
                               'resources': [{'label':plain(label),'url':plain(link)} for label,link in links[1:]]})
    assert len(tasks) == 19 and len({t['id'] for t in tasks}) == 19
    assert len(papers) == len({p['id'] for p in papers})
    assert all(t['question'] for t in tasks)
    bibkeys = set(re.findall(r'^@\w+\{([^,\s]+),', (ROOT/'references.bib').read_text(encoding='utf-8'), re.M))
    assert {p['id'] for p in papers} == bibkeys, 'Reading list and BibTeX coverage differ'
    assert set(coding['papers']) == bibkeys, 'AI-stage coding and BibTeX coverage differ'
    coverage = [{'scope': scope, 'total': sum(p['catalogueScope']==scope for p in papers),
                 'counts': {s:sum(p['catalogueScope']==scope and s in p['stages'] for p in papers) for s in stages}}
                for scope in SCOPES]
    content = '// Generated by scripts/build_catalogue.py from papers/*.md and data/ai-stages.json.\nwindow.MANUFACTURING_CATALOGUE = '+json.dumps({'tasks':tasks,'papers':papers,'stages':stages,'coverage':coverage}, ensure_ascii=False,separators=(',',':'))+';\n'
    buffer = io.StringIO(newline='')
    writer = csv.writer(buffer, lineterminator='\n')
    writer.writerow(['scope','stage','papers','scope_total','share_percent'])
    for row in coverage:
        for stage, count in row['counts'].items():
            writer.writerow([row['scope'], stages[stage], count, row['total'], f"{count/row['total']*100:.4f}"])
    return {OUTPUT:content, ROOT/'docs/assets/coverage.csv':buffer.getvalue()}, len(papers)


if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    outputs,count=build()
    for output,content in outputs.items():
        if args.check:
            if not output.exists() or output.read_text(encoding='utf-8') != content:
                raise SystemExit('Browser catalogue is stale. Run python scripts/build_catalogue.py')
        else:
            output.parent.mkdir(parents=True,exist_ok=True);output.write_text(content,encoding='utf-8')
    print(f'19 tasks / {count} paper entries match the repository bibliography.')
